---
title: Developer turned Designer
timezone: Asia/Bahrain
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: 
    share: true
    related: true
theme: minimal-mistakes-jekyll
locale: en
title_separator: "-"
name: Just add CSS
description: 'I''m a developer that''s trying to learn how to design by learning one
  small design lesson, every single day.

'
url: https://justaddcss.com
baseurl: ''
repository: yazinsai/justaddcss.com
teaser: 
words_per_minute: 200
comments:
  provider: false
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: master
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: docs/_data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: 
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
author:
  name: Yazin Alirhayim
  avatar: 
  bio: Developer, learning to design
  location: Bahrain
  email: hi@justaddcss.com
  uri: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: 
  foursquare: 
  github: 
  gitlab: 
  google_plus: 
  keybase: 
  instagram: 
  lastfm: 
  linkedin: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: 
  vine: 
  weibo: 
  xing: 
  youtube: 
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:title/"
paginate: 10
paginate_path: "/page:num/"
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-redirect-from
- jekyll-archives
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: jekyll-archives
  path: "/categories/"
tag_archive:
  type: jekyll-archives
  path: "/tags/"
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
compress_html:
  clippings: all
  ignore:
    envs: development
